package dev.hiorcraft.nex.discord.permission

enum class DiscordPermission {
    UNKNOWN,

    COMMAND_FAQ,

    COMMAND_TICKET_BUTTONS,

    COMMAND_TICKET_ADD,
    COMMAND_TICKET_ADD_SILENT,
    COMMAND_TICKET_REMOVE,

    TICKET_CLOSE,
    TICKET_CLAIM,
    TICKET_SUPPORT_VIEW,
    TICKET_REPORT_VIEW,
    TICKET_UNBAN_VIEW,
    TICKET_BUG_VIEW,
    TICKET_TEAM_VIEW,
    TICKET_DISCORD_VIEW,
    TICKET_BEWERBUNG_VIEW,

    TICKET_TYPE_BYPASS,

    AUTOMOD_BYPASS,

    COMMAND_SELFROLE_PANEL,
}
