package dev.hexoria.hxo.discord.permission

enum class DiscordPermission {
    UNKNOWN,

    COMMAND_FAQ,

    COMMAND_TICKET_BUTTONS,

    COMMAND_TICKET_ADD,
    COMMAND_TICKET_ADD_SILENT,
    COMMAND_TICKET_REMOVE,
    COMMAND_TICKET_DEADLINE,

    TICKET_CLOSE,
    TICKET_CLAIM,
    TICKET_SUPPORT_VIEW,
    TICKET_REPORT_VIEW,
    TICKET_UNBAN_VIEW,
    TICKET_BUG_VIEW,
    TICKET_TEAM_VIEW,
    TICKET_DISCORD_VIEW,
    TICKET_BEWERBUNG_VIEW,
    TICKET_CONTENT_VIEW,
    TICKET_CONTENT_CREATE,

    TICKET_TYPE_BYPASS,
    TICKET_LIMIT_BYPASS,

    AUTOMOD_BYPASS,

    COMMAND_SELFROLE_PANEL,
    COMMAND_REACTIONROLE_PANEL,
    COMMAND_VOICE_PANEL,
}
